# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dead458c63f54ef8c03a92ab33c917b06d4e2f1127835f3ae28d061db1d9685013641350ffec707258ee9e88d2029c108fe87072e62ebdc6d0815ebb7623ab6e

test:
  secret_key_base: 03e7200960042c13e4145e9697851bb9435671e1f9fe09dd65166ca2561926de06f8dddf5e900aa5deabcc4803b56b9d3b2df0b9747a86edd34b723b1b7e8041

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
